import Head from 'next/head'
import Header from '../components/Header'
import { sanityClient, urlFor } from '../sanity';
import Link from "next/link"
import { useEffect } from 'react';

export default function Home({posts}) {
  useEffect(()=>{
    alert("*please turn on your vpn*")
  },[])
  return (
    <div>
      <Head>
        <title>medium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className='flex items-center flex-col max-w-7xl mx-auto'>

      <div className="flex mb-1 justify-between items-center bg-yellow-400 border-y border-black py-1 lg:py-0 w-full">
        <div className="px-10 space-y-5">
          <h1 className="text-6xl max-w-xl font-serif">
            <span className="underline decoration-black decoration-4">Medium</span> is a place to write, read and connect.
          </h1>
          <h2>
            Est magna mollit in laboris sit nostrud elit voluptate sint non esse duis consequat nulla.
          </h2>
        </div>
        <div>
          <img className="hidden md:inline-flex h-32 lg:h-full" src="https://accountabilitylab.org/wp-content/uploads/2020/03/Medium-logo.png" alt="logo"/>

        </div>
      </div>
      <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 w-full p-5 gap-3 md:gap-6'>
        {
          posts.map((value)=>(
            <Link key={value._id} href={`/post/${value.slug.current}`}>
              <div className='group cursor-pointer flex flex-col justify-between items-center rounded-lg overflow-hidden border'>
                {value.mainImage && <img src={urlFor(value.mainImage).url()} alt={value.title} className="object-cover w-full h-60 group-hover:scale-105 transition-transform duration-200 ease-in-out " />}
                  <div className='flex w-full p-2 bg-white mt-2'>
                  {value.author.image && <img src={urlFor(value.author.image).url()} alt={value.author.name} className="w-12 h-12 rounded-full" />}
                  <div className='flex flex-col ml-4'>
                    <p>{value.title}</p>
                    <p>{value.description}</p>
                  </div>
                  </div>
              </div>
            </Link>
          ))
        }
      </div>
</main>
    </div>
  )
}
export const getServerSideProps = async () => {
  const query = `*[_type == "post"]{
  _id, 
  title ,
  slug ,
      author -> {
      name , 
      image
    },
  description ,
  mainImage ,
  }` ;

  const posts = await sanityClient.fetch(query) ;
  return {
    props : {
      posts
    }
  }
}
